name: Flowzone

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - "master"

jobs:
  flowzone:
    name: Flowzone
    uses: product-os/flowzone/.github/workflows/flowzone.yml@master
    secrets: inherit
    with:
      cloudflare_website: "custom-device-support"
